services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saas_app
    restart: always
    depends_on:
      - db
      - redis
    env_file: .env
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
      - saas_assets:/var/www/public # Compartimos toda la carpeta public
    networks:
      - web_network

  db:
    image: postgres:15-alpine
    container_name: saas_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - saas_db_data:/var/lib/postgresql/data
    networks:
      - web_network

  redis:
    image: redis:alpine
    container_name: saas_redis
    restart: always
    networks:
      - web_network

volumes:
  saas_db_data:
  saas_assets:
    external: true

networks:
  web_network:
    external: true