[supervisord]
logfile=/var/log/supervisord.log ; log principal del sistema supervisor
pidfile=/run/supervisord.pid     ; archivo para rastrear el ID del proceso
nodaemon=false                   ; permite que el script entrypoint siga ejecutándose

[unix_http_server]
file=/run/supervisord.sock       ; el archivo socket que causaba el error 403/no such file
chmod=0700                       ; permisos de acceso al socket

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisord.sock ; le dice al comando 'status' dónde buscar el socket

[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/worker.log
stopwaitsecs=3600
