name: Deploy SaaS to Production

on:
  push:
    branches: [prod]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute remote deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ~/projects/saas
            cd ~/projects/saas

            # 1. Bootstrapping: Get the code if it doesn't exist
            if [ ! -d ".git" ]; then
              git clone -b prod https://github.com/fedrianMF/portfolio-saas.git .
            else
              git fetch origin prod
              git reset --hard origin/prod
            fi

            # 2. Ensure the script is executable
            chmod +x deploy.sh

            # 3. Run the deployment script
            ./deploy.sh